name: Update Ratings

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  update_ratings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Download CSV from S3
        run: |
          mkdir -p input_csv
          aws s3 cp s3://pickle-stats-csv/ input_csv/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1

      - name: List downloaded CSV files
        run: ls -l input_csv

      - name: Run script to update ratings
        run: |
          source venv/bin/activate
          python scripts/elo_ratings.py
          
      - name: Upload JSON to S3
        run: |
          aws s3 cp output_json/ s3://pickle-stats-output/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1